### ISSUE TITLE
메인화면 - 리뷰 지도 화면 구현

### ISSUE THREAD

**Issue by seok20** [replace-project/replace-frontend#13]
## 🔥 Issue

U-100, U-102 화면을 로그인 기능은 제외하고 구현합니다.

## ✅ TODO

- [x] Global-Header 구현
- [x] SideBar 구현
- [x] 네이버 지도 구현
- [x] 리뷰 마커 생성
