### ISSUE TITLE
Global Style 설정 및 가이드라인 작성

### ISSUE THREAD

**Issue by seok20** [replace-project/replace-frontend#5]
## 🔥 Issue

Front-End 협업을 위한 Global Style 설정 및 가이드라인을 작성

## ✅ TODO

- [ ] common-components 구현
- [ ] global style 구현
- [ ] theme style 구현
- [ ] _document.tsx 구현
- [ ] component 구현 시 스타일 가이드라인 작성
